"use client";
import {useAuth} from "@forge/web-kit";
import {useEffect,useState,type FormEvent} from "react";
import {createCodeCase,listOccupancies,type OccupancySummary} from "@/lib/rms-api";
import styles from "../../page.module.css";

export default function NewCodeCasePage(){
 const {me}=useAuth();const [occupancies,setOccupancies]=useState<OccupancySummary[]>([]);const [occupancyId,setOccupancyId]=useState("");const [caseType,setCaseType]=useState("VIOLATION");const [due,setDue]=useState("");const [responsible,setResponsible]=useState("");const [summary,setSummary]=useState("");const [notes,setNotes]=useState("");const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!me?.tenantId)return;void listOccupancies(me.tenantId,{page:"1",pageSize:"200"}).then(r=>{setOccupancies(r.data);if(r.data[0])setOccupancyId(r.data[0].id)}).catch(e=>setError(e instanceof Error?e.message:"Failed to load occupancies"))},[me?.tenantId]);
 async function submit(e:FormEvent){e.preventDefault();if(!me?.tenantId||!occupancyId)return;setSaving(true);setError(null);try{const r=await createCodeCase(me.tenantId,{occupancyId,caseType,status:"OPEN",complianceDueDate:due||null,responsibleParty:responsible||null,summary:summary||null,notes:notes||null});window.location.assign(`/code-enforcement/${r.data.id}/`)}catch(x){setError(x instanceof Error?x.message:"Failed to create enforcement case")}finally{setSaving(false)}}
 return <section className={styles.page}><h1>Open enforcement case</h1>{error?<p className={styles.error}>{error}</p>:null}<form className={styles.form} onSubmit={submit}><div className={styles.formRow}><label>Occupancy<select required value={occupancyId} onChange={e=>setOccupancyId(e.target.value)}>{occupancies.map(o=><option key={o.id} value={o.id}>{o.name} — {o.addressLine1??"No address"}</option>)}</select></label></div><div className={styles.formRow}><label>Case type<select value={caseType} onChange={e=>setCaseType(e.target.value)}><option>VIOLATION</option><option>COMPLAINT</option><option>ORDER</option><option>CITATION</option></select></label></div><div className={styles.formRow}><label>Compliance due date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><div className={styles.formRow}><label>Responsible party<input value={responsible} onChange={e=>setResponsible(e.target.value)}/></label></div><div className={styles.formRow}><label>Summary<textarea rows={4} value={summary} onChange={e=>setSummary(e.target.value)}/></label></div><div className={styles.formRow}><label>Notes<textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button className={styles.button} disabled={saving||!occupancyId}>{saving?"Opening…":"Open case"}</button></form></section>
}