"use client";
import Link from "next/link";
import {useAuth} from "@forge/web-kit";
import {useCallback,useEffect,useMemo,useState} from "react";
import {listPersons,listPersonnel,listScheduleAssignments,listShiftSwaps,listTimeOffRequests,patchShiftSwap,patchTimeOffRequest,type PersonSummary,type RmsPersonnelSummary,type ScheduleAssignment,type ShiftSwapRequest,type TimeOffRequest} from "@/lib/rms-api";
import styles from "../page.module.css";

export default function SchedulingPage(){
 const {me}=useAuth();
 const [assignments,setAssignments]=useState<ScheduleAssignment[]>([]); const [leave,setLeave]=useState<TimeOffRequest[]>([]); const [swaps,setSwaps]=useState<ShiftSwapRequest[]>([]);
 const [personnel,setPersonnel]=useState<RmsPersonnelSummary[]>([]); const [persons,setPersons]=useState<PersonSummary[]>([]); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!me?.tenantId)return;setError(null);try{const [a,l,s,p,people]=await Promise.all([listScheduleAssignments(me.tenantId,{page:"1",pageSize:"200"}),listTimeOffRequests(me.tenantId,{page:"1",pageSize:"100"}),listShiftSwaps(me.tenantId,{page:"1",pageSize:"100"}),listPersonnel(me.tenantId,{page:"1",pageSize:"200"}),listPersons(me.tenantId)]);setAssignments(a.data);setLeave(l.data);setSwaps(s.data);setPersonnel(p.data);setPersons(people.data)}catch(e){setError(e instanceof Error?e.message:"Failed to load scheduling")} },[me?.tenantId]);
 useEffect(()=>{void load()},[load]);
 const personName=useMemo(()=>{const names=new Map(persons.map(p=>[p.id,p.displayName]));return new Map(personnel.map(p=>[p.id,names.get(p.personId)??p.personId]))},[personnel,persons]);
 async function reviewLeave(row:TimeOffRequest,status:"APPROVED"|"DENIED"){if(!me?.tenantId)return;setBusy(true);try{await patchTimeOffRequest(me.tenantId,row.id,{status,reviewer:me.userId},row.recordVersion);await load()}catch(e){setError(e instanceof Error?e.message:"Failed to review time off")}finally{setBusy(false)}}
 async function reviewSwap(row:ShiftSwapRequest,status:"APPROVED"|"DENIED"){if(!me?.tenantId)return;setBusy(true);try{await patchShiftSwap(me.tenantId,row.id,{status,reviewer:me.email??"Scheduler"},row.recordVersion);await load()}catch(e){setError(e instanceof Error?e.message:"Failed to review shift swap")}finally{setBusy(false)}}
 return <section className={styles.page}><h1>Scheduling</h1><p className={styles.lead}>Duty assignments, overtime, leave, swap requests, and qualification-aware staffing.</p>
 <div className={styles.actions}><Link className={styles.button} href="/scheduling/new/">Add assignment</Link><Link className={styles.button} href="/scheduling/time-off/new/">Request time off</Link><Link className={styles.button} href="/scheduling/swaps/new/">Request shift swap</Link></div>
 {error?<p className={styles.error}>{error}</p>:null}
 <div className={styles.panel}><h2>Assignments</h2>{assignments.length?<table className={styles.table}><thead><tr><th>Personnel</th><th>Start</th><th>End</th><th>Type</th><th>Role</th><th>Status</th><th>Readiness</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{personName.get(a.personnelId)??a.personnelId}</td><td>{new Date(a.startAt).toLocaleString()}</td><td>{new Date(a.endAt).toLocaleString()}</td><td>{a.assignmentType}</td><td>{a.role??"—"}</td><td>{a.status}</td><td>{a.eligibilityStatus}{a.eligibilityWarningsJson.length?" · "+a.eligibilityWarningsJson.join("; "):""}</td></tr>)}</tbody></table>:<p className={styles.muted}>No schedule assignments.</p>}</div>
 <div className={styles.panel}><h2>Time off</h2>{leave.length?<table className={styles.table}><thead><tr><th>Personnel</th><th>Type</th><th>Start</th><th>End</th><th>Status</th><th>Actions</th></tr></thead><tbody>{leave.map(r=><tr key={r.id}><td>{personName.get(r.personnelId)??r.personnelId}</td><td>{r.leaveType}</td><td>{new Date(r.startAt).toLocaleString()}</td><td>{new Date(r.endAt).toLocaleString()}</td><td>{r.status}</td><td>{r.status==="PENDING"?<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>void reviewLeave(r,"APPROVED")}>Approve</button><button className={styles.button} disabled={busy} onClick={()=>void reviewLeave(r,"DENIED")}>Deny</button></div>:"—"}</td></tr>)}</tbody></table>:<p className={styles.muted}>No time-off requests.</p>}</div>
 <div className={styles.panel}><h2>Shift swaps</h2>{swaps.length?<table className={styles.table}><thead><tr><th>Requester</th><th>Replacement</th><th>Status</th><th>Reason</th><th>Actions</th></tr></thead><tbody>{swaps.map(r=><tr key={r.id}><td>{personName.get(r.requesterPersonnelId)??r.requesterPersonnelId}</td><td>{r.replacementPersonnelId?personName.get(r.replacementPersonnelId)??r.replacementPersonnelId:"—"}</td><td>{r.status}</td><td>{r.reason??"—"}</td><td>{r.status==="PENDING"?<div className={styles.actions}><button className={styles.button} disabled={busy||!r.replacementPersonnelId} onClick={()=>void reviewSwap(r,"APPROVED")}>Approve</button><button className={styles.button} disabled={busy} onClick={()=>void reviewSwap(r,"DENIED")}>Deny</button></div>:"—"}</td></tr>)}</tbody></table>:<p className={styles.muted}>No shift-swap requests.</p>}</div>
 </section>
}
