"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useAuth} from "@forge/web-kit";
import {useEffect,useState} from "react";
import {
  addInvestigationCustodyEvent,createInvestigationEvidence,getInvestigation,patchInvestigation,
  type InvestigationDetail,type InvestigationEvidence
} from "@/lib/rms-api";
import styles from "../../page.module.css";

export default function InvestigationDetailPage(){
 const {me}=useAuth();const {id}=useParams<{id:string}>();const [detail,setDetail]=useState<InvestigationDetail|null>(null);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
 const [area,setArea]=useState("");const [cause,setCause]=useState("UNDETERMINED");const [narrative,setNarrative]=useState("");const [disposition,setDisposition]=useState("");
 const [evType,setEvType]=useState("PHOTO");const [tag,setTag]=useState("");const [evTitle,setEvTitle]=useState("");const [custodian,setCustodian]=useState("");const [storage,setStorage]=useState("");
 const [transferEvidence,setTransferEvidence]=useState("");const [transferTo,setTransferTo]=useState("");const [transferLocation,setTransferLocation]=useState("");
 const [reviewer,setReviewer]=useState("");const [reviewNotes,setReviewNotes]=useState("");

 async function load(){if(!me?.tenantId)return;try{const d=await getInvestigation(me.tenantId,id);setDetail(d);setArea(d.case.areaOfOrigin??"");setCause(d.case.causeClassification??"UNDETERMINED");setNarrative(d.case.causeNarrative??"");setDisposition(d.case.disposition??"");setReviewer(d.case.supervisorReviewer??"");setReviewNotes(d.case.supervisorNotes??"");if(!transferEvidence&&d.evidence[0])setTransferEvidence(d.evidence[0].id)}catch(e){setError(e instanceof Error?e.message:"Failed to load investigation")}}
 useEffect(()=>{void load()},[me?.tenantId,id]);

 async function saveAnalysis(){if(!me?.tenantId||!detail)return;setSaving(true);setError(null);try{const r=await patchInvestigation(me.tenantId,id,{status:"ANALYSIS",areaOfOrigin:area||null,causeClassification:cause||null,causeNarrative:narrative||null,disposition:disposition||null},detail.case.recordVersion);setDetail({...detail,case:r.data});setMessage("Investigation analysis saved.")}catch(e){setError(e instanceof Error?e.message:"Failed to save analysis")}finally{setSaving(false)}}
 async function addEvidence(){if(!me?.tenantId||!detail||!tag.trim())return;setSaving(true);setError(null);try{const e=await createInvestigationEvidence(me.tenantId,id,{evidenceType:evType,tagNumber:tag.trim(),title:evTitle||null,collectedAt:new Date().toISOString(),collectedBy:custodian||null,currentCustodian:custodian||null,storageLocation:storage||null,status:"IN_CUSTODY"});setDetail({...detail,evidence:[e,...detail.evidence]});setTag("");setEvTitle("");if(!transferEvidence)setTransferEvidence(e.id);setMessage("Evidence item added.")}catch(e){setError(e instanceof Error?e.message:"Failed to add evidence")}finally{setSaving(false)}}
 async function transfer(){if(!me?.tenantId||!detail||!transferEvidence)return;setSaving(true);setError(null);try{const evidence=detail.evidence.find(e=>e.id===transferEvidence);const r=await addInvestigationCustodyEvent(me.tenantId,transferEvidence,{action:"TRANSFERRED",occurredAt:new Date().toISOString(),fromCustodian:evidence?.currentCustodian??null,toCustodian:transferTo||null,location:transferLocation||null});setDetail({...detail,evidence:detail.evidence.map(e=>e.id===r.evidence.id?r.evidence:e),custodyEvents:[r.event,...detail.custodyEvents]});setTransferTo("");setTransferLocation("");setMessage("Chain-of-custody event recorded.")}catch(e){setError(e instanceof Error?e.message:"Failed to record custody transfer")}finally{setSaving(false)}}
 async function review(status:"PENDING"|"APPROVED"|"RETURNED"){if(!me?.tenantId||!detail)return;setSaving(true);setError(null);try{const r=await patchInvestigation(me.tenantId,id,{supervisorReviewStatus:status,supervisorReviewer:reviewer||null,supervisorNotes:reviewNotes||null},detail.case.recordVersion);setDetail({...detail,case:r.data});setMessage(`Supervisor review marked ${status.toLowerCase()}.`)}catch(e){setError(e instanceof Error?e.message:"Failed to update supervisor review")}finally{setSaving(false)}}
 async function closeCase(){if(!me?.tenantId||!detail)return;setSaving(true);setError(null);try{const r=await patchInvestigation(me.tenantId,id,{status:"CLOSED"},detail.case.recordVersion);setDetail({...detail,case:r.data});setMessage("Investigation closed.")}catch(e){setError(e instanceof Error?e.message:"Investigation cannot be closed")}finally{setSaving(false)}}

 if(!detail)return <section className={styles.page}>{error?<p className={styles.error}>{error}</p>:<p className={styles.muted}>Loading investigation…</p>}</section>;
 const record=detail.case;
 return <section className={styles.page}><h1>{record.caseNumber}</h1><p className={styles.lead}>{record.caseType} · {record.status} · Lead: {record.leadInvestigator??"Unassigned"}</p>
 <div className={styles.actions}>{record.incidentId?<Link className={styles.button} href={`/incidents/${record.incidentId}/`}>Open incident</Link>:null}{record.occupancyId?<Link className={styles.button} href={`/occupancies/${record.occupancyId}/`}>Open occupancy</Link>:null}{record.supervisorReviewStatus==="APPROVED"&&record.status!=="CLOSED"?<button className={styles.button} disabled={saving} onClick={()=>void closeCase()}>Close investigation</button>:null}</div>
 {error?<p className={styles.error}>{error}</p>:null}{message?<p>{message}</p>:null}
 <div className={styles.panel}><h2>Scene</h2><dl><dt>Location</dt><dd>{record.location??"—"}</dd><dt>Scene status</dt><dd>{record.sceneStatus??"—"}</dd><dt>Weather</dt><dd>{record.weather??"—"}</dd><dt>Initial observations</dt><dd>{record.initialObservations??"—"}</dd></dl></div>
 <div className={styles.panel}><h2>Origin & cause analysis</h2><div className={styles.form}><div className={styles.formRow}><label>Area of origin<textarea rows={3} value={area} onChange={e=>setArea(e.target.value)}/></label></div><div className={styles.formRow}><label>Cause classification<select value={cause} onChange={e=>setCause(e.target.value)}><option>UNDETERMINED</option><option>ACCIDENTAL</option><option>INCENDIARY</option><option>NATURAL</option><option>OTHER</option></select></label></div><div className={styles.formRow}><label>Cause narrative<textarea rows={7} value={narrative} onChange={e=>setNarrative(e.target.value)}/></label></div><div className={styles.formRow}><label>Disposition<input value={disposition} onChange={e=>setDisposition(e.target.value)}/></label></div><button type="button" className={styles.button} disabled={saving} onClick={()=>void saveAnalysis()}>Save analysis</button></div></div>
 <div className={styles.panel}><h2>Evidence</h2><div className={styles.form}><div className={styles.formRow}><label>Evidence type<select value={evType} onChange={e=>setEvType(e.target.value)}><option>PHOTO</option><option>PHYSICAL</option><option>DOCUMENT</option><option>INTERVIEW</option><option>VIDEO</option><option>OTHER</option></select></label></div><div className={styles.formRow}><label>Tag number<input value={tag} onChange={e=>setTag(e.target.value)}/></label></div><div className={styles.formRow}><label>Title<input value={evTitle} onChange={e=>setEvTitle(e.target.value)}/></label></div><div className={styles.formRow}><label>Custodian<input value={custodian} onChange={e=>setCustodian(e.target.value)}/></label></div><div className={styles.formRow}><label>Storage location<input value={storage} onChange={e=>setStorage(e.target.value)}/></label></div><button type="button" className={styles.button} disabled={saving||!tag.trim()} onClick={()=>void addEvidence()}>Add evidence</button></div>
 {detail.evidence.length?<table className={styles.table}><thead><tr><th>Tag</th><th>Type</th><th>Title</th><th>Custodian</th><th>Storage</th><th>Status</th></tr></thead><tbody>{detail.evidence.map((e:InvestigationEvidence)=><tr key={e.id}><td className={styles.mono}>{e.tagNumber}</td><td>{e.evidenceType}</td><td>{e.title??"—"}</td><td>{e.currentCustodian??"—"}</td><td>{e.storageLocation??"—"}</td><td>{e.status}</td></tr>)}</tbody></table>:<p className={styles.muted}>No evidence items.</p>}</div>
 <div className={styles.panel}><h2>Chain of custody</h2><div className={styles.form}><div className={styles.formRow}><label>Evidence<select value={transferEvidence} onChange={e=>setTransferEvidence(e.target.value)}><option value="">Select evidence</option>{detail.evidence.map(e=><option key={e.id} value={e.id}>{e.tagNumber} — {e.title??e.evidenceType}</option>)}</select></label></div><div className={styles.formRow}><label>Transfer to<input value={transferTo} onChange={e=>setTransferTo(e.target.value)}/></label></div><div className={styles.formRow}><label>Storage/location<input value={transferLocation} onChange={e=>setTransferLocation(e.target.value)}/></label></div><button type="button" className={styles.button} disabled={saving||!transferEvidence} onClick={()=>void transfer()}>Record transfer</button></div>
 {detail.custodyEvents.length?<table className={styles.table}><thead><tr><th>Time</th><th>Evidence</th><th>Action</th><th>From</th><th>To</th><th>Location</th></tr></thead><tbody>{detail.custodyEvents.map(e=><tr key={e.id}><td>{new Date(e.occurredAt).toLocaleString()}</td><td>{detail.evidence.find(x=>x.id===e.evidenceId)?.tagNumber??e.evidenceId}</td><td>{e.action}</td><td>{e.fromCustodian??"—"}</td><td>{e.toCustodian??"—"}</td><td>{e.location??"—"}</td></tr>)}</tbody></table>:<p className={styles.muted}>No custody events.</p>}</div>
 <div className={styles.panel}><h2>Supervisor review</h2><div className={styles.form}><div className={styles.formRow}><label>Reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label></div><div className={styles.formRow}><label>Review notes<textarea rows={5} value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)}/></label></div><div className={styles.actions}><button type="button" className={styles.button} disabled={saving} onClick={()=>void review("PENDING")}>Submit for review</button><button type="button" className={styles.button} disabled={saving} onClick={()=>void review("APPROVED")}>Approve</button><button type="button" className={styles.button} disabled={saving} onClick={()=>void review("RETURNED")}>Return</button></div></div><p>Current review status: {record.supervisorReviewStatus}</p></div>
 </section>
}
