"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useAuth} from "@forge/web-kit";
import {useEffect,useState} from "react";
import {
  getCodeCase,getOccupancyDetail,issueCodeNotice,patchCodeCase,patchCodeViolation,
  type CodeCaseDetail,type CodeViolation,type OccupancyDetail
} from "@/lib/rms-api";
import styles from "../../page.module.css";

export default function CodeCaseDetailPage(){
 const {me}=useAuth();const {id}=useParams<{id:string}>();const [detail,setDetail]=useState<CodeCaseDetail|null>(null);const [occupancy,setOccupancy]=useState<OccupancyDetail|null>(null);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
 const [noticeType,setNoticeType]=useState("NOTICE_OF_VIOLATION");const [recipient,setRecipient]=useState("");const [subject,setSubject]=useState("");const [body,setBody]=useState("");
 async function load(){if(!me?.tenantId)return;try{const d=await getCodeCase(me.tenantId,id);setDetail(d);setOccupancy(await getOccupancyDetail(me.tenantId,d.case.occupancyId))}catch(e){setError(e instanceof Error?e.message:"Failed to load enforcement case")}}
 useEffect(()=>{void load()},[me?.tenantId,id]);
 async function updateViolation(v:CodeViolation,status:"CORRECTED"|"VERIFIED"|"VOID"){if(!me?.tenantId||!detail)return;setSaving(true);setError(null);try{const u=await patchCodeViolation(me.tenantId,v.id,{status},v.recordVersion);setDetail({...detail,violations:detail.violations.map(x=>x.id===v.id?u:x)});setMessage(`Violation marked ${status.toLowerCase()}.`)}catch(e){setError(e instanceof Error?e.message:"Failed to update violation")}finally{setSaving(false)}}
 async function sendNotice(){if(!me?.tenantId||!detail||!body.trim())return;setSaving(true);setError(null);try{const r=await issueCodeNotice(me.tenantId,id,{noticeType,recipient:recipient||null,subject:subject||null,bodySnapshot:body,deliveryMethod:"OTHER"});setDetail({...detail,case:r.case,notices:[r.notice,...detail.notices]});setBody("");setSubject("");setMessage("Notice issued and snapshotted.")}catch(e){setError(e instanceof Error?e.message:"Failed to issue notice")}finally{setSaving(false)}}
 async function closeCase(){if(!me?.tenantId||!detail)return;setSaving(true);setError(null);try{const r=await patchCodeCase(me.tenantId,id,{status:"CLOSED"},detail.case.recordVersion);setDetail({...detail,case:r.data});setMessage("Case closed.")}catch(e){setError(e instanceof Error?e.message:"Case cannot be closed")}finally{setSaving(false)}}
 if(!detail)return <section className={styles.page}>{error?<p className={styles.error}>{error}</p>:<p className={styles.muted}>Loading case…</p>}</section>;
 const record=detail.case;const unresolved=detail.violations.filter(v=>v.status!=="VERIFIED"&&v.status!=="VOID");
 return <section className={styles.page}><h1>{record.caseNumber}</h1><p className={styles.lead}>{occupancy?.name??record.occupancyId} · {record.status} · {record.caseType}</p>
 <div className={styles.actions}><Link className={styles.button} href={`/occupancies/${record.occupancyId}/`}>Open occupancy</Link>{record.inspectionId?<Link className={styles.button} href={`/inspections/${record.inspectionId}/`}>Open inspection</Link>:null}{record.status!=="CLOSED"&&record.status!=="VOID"?<button className={styles.button} disabled={saving||unresolved.length>0} onClick={()=>void closeCase()}>Close case</button>:null}</div>
 {error?<p className={styles.error}>{error}</p>:null}{message?<p>{message}</p>:null}
 <div className={styles.panel}><h2>Case summary</h2><dl><dt>Status</dt><dd>{record.status}</dd><dt>Opened</dt><dd>{new Date(record.openedAt).toLocaleString()}</dd><dt>Compliance due</dt><dd>{record.complianceDueDate??"—"}</dd><dt>Responsible party</dt><dd>{record.responsibleParty??"—"}</dd><dt>Summary</dt><dd>{record.summary??"—"}</dd><dt>Unresolved violations</dt><dd>{unresolved.length}</dd></dl></div>
 <div className={styles.panel}><h2>Violations</h2>{detail.violations.length?<table className={styles.table}><thead><tr><th>Violation</th><th>Code</th><th>Severity</th><th>Status</th><th>Due</th><th>Corrective action</th><th>Action</th></tr></thead><tbody>{detail.violations.map(v=><tr key={v.id}><td>{v.title}</td><td>{v.codeReference??"—"}</td><td>{v.severity}</td><td>{v.status}</td><td>{v.correctionDueDate??"—"}</td><td>{v.correctiveAction??"—"}</td><td>{v.status==="OPEN"?<button className={styles.button} disabled={saving} onClick={()=>void updateViolation(v,"CORRECTED")}>Mark corrected</button>:v.status==="CORRECTED"?<button className={styles.button} disabled={saving} onClick={()=>void updateViolation(v,"VERIFIED")}>Verify</button>:v.status==="VERIFIED"?"Closed":v.status}</td></tr>)}</tbody></table>:<p className={styles.muted}>No violations recorded.</p>}</div>
 <div className={styles.panel}><h2>Issue notice</h2><div className={styles.form}><div className={styles.formRow}><label>Notice type<select value={noticeType} onChange={e=>setNoticeType(e.target.value)}><option>WARNING</option><option>NOTICE_OF_VIOLATION</option><option>ORDER_TO_CORRECT</option><option>CITATION</option></select></label></div><div className={styles.formRow}><label>Recipient<input value={recipient} onChange={e=>setRecipient(e.target.value)}/></label></div><div className={styles.formRow}><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label></div><div className={styles.formRow}><label>Notice body<textarea rows={10} value={body} onChange={e=>setBody(e.target.value)}/></label></div><button type="button" className={styles.button} disabled={saving||!body.trim()} onClick={()=>void sendNotice()}>Issue notice</button></div></div>
 <div className={styles.panel}><h2>Notice history</h2>{detail.notices.length?<table className={styles.table}><thead><tr><th>Date</th><th>Type</th><th>Recipient</th><th>Delivery</th><th>Subject</th></tr></thead><tbody>{detail.notices.map(n=><tr key={n.id}><td>{new Date(n.issuedAt).toLocaleString()}</td><td>{n.noticeType}</td><td>{n.recipient??"—"}</td><td>{n.deliveryMethod??"—"}</td><td>{n.subject??"—"}</td></tr>)}</tbody></table>:<p className={styles.muted}>No notices issued.</p>}</div>
 </section>
}
