import type { ForgeNavigationGroup } from "@forge/design-system";

/** Creator Console primary navigation (configuration-driven). */
export const CREATOR_NAV_GROUPS: ForgeNavigationGroup[] = [
  {
    id: "overview",
    label: "Overview",
    items: [
      { id: "dashboard", label: "Dashboard", route: "/" },
      { id: "health", label: "Platform health", route: "/health" },
      { id: "deployment", label: "Deployment", route: "/deployment" },
      { id: "migrations", label: "Data migration", route: "/migrations" },
    ],
  },
  {
    id: "access",
    label: "Access",
    items: [
      { id: "login", label: "Login", route: "/login" },
      { id: "select-tenant", label: "Select tenant", route: "/select-tenant" },
      { id: "invitations", label: "Invitations", route: "/invitations" },
      { id: "memberships", label: "Memberships", route: "/memberships" },
      { id: "onboarding", label: "Onboarding", route: "/onboarding" },
    ],
  },
  {
    id: "platform",
    label: "Platform",
    items: [
      { id: "tenants", label: "Tenants", route: "/tenants" },
      { id: "organizations", label: "Organizations", route: "/organizations" },
      { id: "persons", label: "Persons", route: "/persons" },
      { id: "users", label: "Users", route: "/users" },
      { id: "roles", label: "Roles", route: "/roles" },
      { id: "permissions", label: "Permissions", route: "/permissions" },
    ],
  },
  {
    id: "catalog",
    label: "Catalog",
    items: [
      { id: "products", label: "Products", route: "/products" },
      { id: "entitlements", label: "Entitlements", route: "/entitlements" },
      { id: "subscriptions", label: "Subscriptions", route: "/subscriptions" },
      { id: "billing", label: "Billing", route: "/billing" },
      { id: "features", label: "Feature flags", route: "/features" },
    ],
  },
  {
    id: "neris",
    label: "NERIS Schema",
    items: [
      { id: "neris-packages", label: "Packages", route: "/neris/packages" },
      { id: "neris-versions", label: "Versions", route: "/neris/versions" },
      { id: "neris-modules", label: "Modules", route: "/neris/modules" },
      { id: "neris-fields", label: "Fields", route: "/neris/fields" },
      { id: "neris-value-sets", label: "Value sets", route: "/neris/value-sets" },
      { id: "neris-conditions", label: "Conditions", route: "/neris/conditions" },
      { id: "neris-mappings", label: "Mappings", route: "/neris/mappings" },
      { id: "neris-validation", label: "Validation", route: "/neris/validation" },
    ],
  },
  {
    id: "studio",
    label: "Configuration Studio",
    items: [
      { id: "studio-home", label: "Studio home", route: "/studio" },
      { id: "studio-tenant", label: "Tenant Profile", route: "/studio/tenant-profile" },
      { id: "studio-org", label: "Organization Profile", route: "/studio/organization-profile" },
      { id: "studio-branding", label: "Branding", route: "/studio/branding" },
      { id: "studio-navigation", label: "Navigation", route: "/studio/navigation" },
      { id: "studio-terminology", label: "Terminology", route: "/studio/terminology" },
      { id: "studio-modules", label: "Modules", route: "/studio/modules" },
      { id: "studio-features", label: "Features", route: "/studio/features" },
      { id: "studio-dropdowns", label: "Dropdowns", route: "/studio/dropdowns" },
      { id: "studio-custom-fields", label: "Custom fields", route: "/studio/custom-fields" },
      { id: "studio-forms", label: "Forms", route: "/studio/forms" },
      { id: "studio-workflows", label: "Workflows", route: "/studio/workflows" },
      { id: "studio-roles", label: "Roles", route: "/studio/roles" },
      { id: "studio-permissions", label: "Permissions", route: "/studio/permissions" },
      { id: "studio-notification-templates", label: "Notification templates", route: "/studio/notification-templates" },
      { id: "studio-email-templates", label: "Email templates", route: "/studio/email-templates" },
      { id: "studio-document-templates", label: "Document templates", route: "/studio/document-templates" },
      { id: "studio-certificate-templates", label: "Certificate templates", route: "/studio/certificate-templates" },
      { id: "studio-dashboards", label: "Dashboards", route: "/studio/dashboards" },
      { id: "studio-reporting", label: "Reporting", route: "/studio/reporting" },
      { id: "studio-import-config", label: "Import config", route: "/studio/import-config" },
      { id: "studio-export-config", label: "Export config", route: "/studio/export-config" },
      { id: "studio-security", label: "Security", route: "/studio/security" },
      { id: "studio-retention", label: "Retention", route: "/studio/retention" },
      { id: "studio-business-hours", label: "Business hours", route: "/studio/business-hours" },
      { id: "studio-holiday-calendar", label: "Holiday calendar", route: "/studio/holiday-calendar" },
      { id: "studio-facilities", label: "Facilities", route: "/studio/facilities" },
      { id: "studio-locations", label: "Locations", route: "/studio/locations" },
    ],
  },
  {
    id: "ai",
    label: "AI Management",
    items: [
      { id: "ai-overview", label: "Overview", route: "/ai" },
      { id: "ai-providers", label: "Providers", route: "/ai/providers" },
      { id: "ai-models", label: "Models", route: "/ai/models" },
      { id: "ai-tenant-access", label: "Tenant Access", route: "/ai/tenant-access" },
      { id: "ai-feature-status", label: "Feature Status", route: "/ai/feature-status" },
      { id: "ai-templates", label: "Templates", route: "/ai/templates" },
      { id: "ai-policies", label: "Policies", route: "/ai/policies" },
      { id: "ai-usage", label: "Usage", route: "/ai/usage" },
      { id: "ai-audit", label: "Audit", route: "/ai/audit" },
    ],
  },
  {
    id: "imports",
    label: "Import Center",
    items: [{ id: "import-center", label: "Import Center", route: "/imports" }],
  },
  {
    id: "settings",
    label: "Creator Settings",
    items: [
      { id: "branding", label: "Legacy branding", route: "/branding" },
      { id: "configuration", label: "Legacy key/value", route: "/configuration" },
      { id: "audit", label: "Audit", route: "/audit" },
    ],
  },
];
